finish containers envs with tests em report with sonar

diff --git a/.github/workflows/.ci-cd.yml b/.github/workflows/.ci-cd.yml
--- a/.github/workflows/.ci-cd.yml
+++ b/.github/workflows/.ci-cd.yml
@@ -72,14 +72,14 @@ jobs:
         run: printf "%s\n" "${{ secrets.ENV }}" > .env
 
       # 3️⃣ Start containers, wait for DB, apply migrations & seed and prepare node enviroment for Vitest
-      - name: Set up Docker Compose
+      - name: Set up Stage Docker Compose
         env:
           DATABASE_URL: postgresql://dart:${{ secrets.POSTGRES_PASSWORD }}@db:5432/postgresdb
           POSTGRES_USER: dart
           POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
           POSTGRES_DB: postgresdb
           PORT: 3000
-        run: docker compose --profile test up --build -d
+        run: docker compose --profile stage up --build -d
 
       - name: Wait for PostgreSQL
         run: |
@@ -104,11 +104,27 @@ jobs:
       # 4️⃣ Run tests (coverage)
       - name: Run tests (unit & integration)
         run: docker compose exec -T app4 bun run test:coverage
-      # 5️⃣ Tear down Docker containers
+      # 5️⃣ Copiar pasta de coverage do container para o host
+      - name: Copy coverage folder
+        run: docker cp $(docker compose ps -q app4):/usr/src/app/coverage ./coverage
+
+      # 6️⃣ Instalar sonar-scanner e dependências
+      - name: Set up SonarQube scanner
+        uses: sonarsource/sonarcloud-github-action@v2
+        with:
+          args: >
+            -Dsonar.organization=devdartjs
+            -Dsonar.projectKey=Virtus-backend
+            -Dsonar.host.url=https://sonarcloud.io
+            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
+            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
+
+      # 7️⃣ Tear down Docker containers
       - name: Tear down containers
+        if: always()
         run: docker compose down --volumes --remove-orphans
 
-      # 6️⃣ Clean up the .env file
+      # 8️⃣ Clean up the .env file
       - name: Cleanup .env
         run: rm -f .env
 
@@ -156,49 +172,49 @@ jobs:
 
       # 7️⃣ Push Docker images
       - name: Push Docker images
-        run: docker push dartw/virtus-backend:${{ github.sha }} && docker push dartw/virtus-backend:dev
+        run: docker push dartw/virtus-backend:${{ github.sha }} && docker push dartw/virtus-backend:stage
 
       - name: Cleanup .env
         run: rm -f .env
 
-  deploy-stage:
-    name: Deploy to Stage
-    runs-on: ubuntu-latest
-    needs: build-and-push-image
+  # deploy-stage:
+  #   name: Deploy to Stage
+  #   runs-on: ubuntu-latest
+  #   needs: build-and-push-image
 
-    steps:
-      # 1️⃣ Checkout repository
-      - name: Checkout repository
-        uses: actions/checkout@v3
+  #   steps:
+  #     # 1️⃣ Checkout repository
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v3
 
-      # 2️⃣ Install Fly CLI
-      - name: Install Flyctl
-        run: |
-          curl -L https://fly.io/install.sh | sh
-          echo "$HOME/.fly/bin" >> $GITHUB_PATH
+  #     # 2️⃣ Install Fly CLI
+  #     - name: Install Flyctl
+  #       run: |
+  #         curl -L https://fly.io/install.sh | sh
+  #         echo "$HOME/.fly/bin" >> $GITHUB_PATH
 
-      # 3️⃣ Login to Fly.io
-      - name: Fly login using token
-        env:
-          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_VIRTUS_BACKEND }}
-        run: flyctl auth token
+  #     # 3️⃣ Login to Fly.io
+  #     - name: Fly login using token
+  #       env:
+  #         FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_VIRTUS_BACKEND }}
+  #       run: flyctl auth token
 
-      # 4️⃣ Deploy Docker image to Fly.io stage
-      - name: Deploy to stage
-        env:
-          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_VIRTUS_BACKEND }}
-        run: |
-          flyctl deploy \
-            --app my-app-stage \
-            --image dartw/virtus-backend:dev \
-            --region gru \
-            --strategy immediate
+  #     # 4️⃣ Deploy Docker image to Fly.io stage
+  #     - name: Deploy to stage
+  #       env:
+  #         FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_VIRTUS_BACKEND }}
+  #       run: |
+  #         flyctl deploy \
+  #           --app my-app-stage \
+  #           --image dartw/virtus-backend:dev \
+  #           --region gru \
+  #           --strategy immediate
 
-      # 5️⃣ Optional: wait a few seconds for the app to become healthy
-      - name: Wait for app
-        run: sleep 10
+  #     # 5️⃣ Optional: wait a few seconds for the app to become healthy
+  #     - name: Wait for app
+  #       run: sleep 10
 
-      # 6️⃣ Run stage smoke tests (optional)
-      - name: Run stage smoke tests
-        run: |
-          curl -f https://api.my-app.fly/health || exit 1
+  #     # 6️⃣ Run stage smoke tests (optional)
+  #     - name: Run stage smoke tests
+  #       run: |
+  #         curl -f https://api.my-app.fly/health || exit 1
