use postgres-neon and redis-upstash for deploy in stage environment

diff --git a/.github/workflows/.ci-cd.yml b/.github/workflows/.ci-cd.yml
--- a/.github/workflows/.ci-cd.yml
+++ b/.github/workflows/.ci-cd.yml
@@ -10,124 +10,116 @@ on:
       - main
 
 jobs:
-  # build-and-test:
-  #   name: Build & Unit Tests
-  #   runs-on: ubuntu-latest
+  build-and-test:
+    name: Build & Unit Tests
+    runs-on: ubuntu-latest
 
-  #   steps:
-  #     # 1️⃣ Checkout repository
-  #     - name: Checkout repository
-  #       uses: actions/checkout@v3
+    steps:
+      # 1️⃣ Checkout repository
+      - name: Checkout repository
+        uses: actions/checkout@v3
 
-  #     # 2️⃣ Cache Bun runtime
-  #     - name: Cache Bun
-  #       uses: actions/cache@v3
-  #       with:
-  #         path: ~/.bun
-  #         key: bun-${{ runner.os }}-${{ hashFiles('bun.lock') }}
+      # 2️⃣ Cache Bun runtime
+      - name: Cache Bun
+        uses: actions/cache@v3
+        with:
+          path: ~/.bun
+          key: bun-${{ runner.os }}-${{ hashFiles('bun.lock') }}
 
-  #     # 3️⃣ Install Bun
-  #     - name: Install Bun
-  #       run: |
-  #         curl -fsSL https://bun.sh/install | BUN_INSTALL_VERSION=1.9.0 bash
-  #         echo "$HOME/.bun/bin" >> $GITHUB_PATH
+      # 3️⃣ Install Bun
+      - name: Install Bun
+        run: |
+          curl -fsSL https://bun.sh/install | BUN_INSTALL_VERSION=1.9.0 bash
+          echo "$HOME/.bun/bin" >> $GITHUB_PATH
 
-  #     # 4️⃣ Install dependencies
-  #     - name: Install dependencies
-  #       run: bun install
-  #     - name: Reinstall @prisma/client
-  #       run: bun add @prisma/client
+      # 4️⃣ Install dependencies
+      - name: Install dependencies
+        run: bun install
 
-  #     # 5️⃣ Build the app
-  #     - name: Build app
-  #       run: bun run build
+      - name: Install Install Prisma CLI + Client
+        run: bun add prisma@6.12.0 @prisma/client@6.16.2
 
-  #     # 6️⃣ Check code format
-  #     - name: Check code format
-  #       run: npx prettier --check src/**/*.ts
+      - name: Generate Prisma client
+        run: bunx prisma generate
 
-  #     # 7️⃣ Lint
-  #     - name: Run ESLint
-  #       run: bun run lint
+      - name: Show Bun version
+        run: bun --version
 
-  #     # 8️⃣ Generate Prisma client
-  #     - name: Generate Prisma client
-  #       run: bunx prisma generate
+      # 5️⃣ Build the app
+      - name: Build app
+        run: bun run build
 
-  #     # 9️⃣ Run unit tests
-  #     - name: Run unit tests
-  #       run: bun run test:unit
+      # 6️⃣ Check code format
+      - name: Check code format
+        run: npx prettier --check src/**/*.ts
 
-  # integration-tests:
-  #   name: Run Integration Tests in Docker
-  #   runs-on: ubuntu-latest
-  #   needs: build-and-test
+      # 7️⃣ Lint
+      - name: Run ESLint
+        run: bun run lint
 
-  #   steps:
-  #     # 1️⃣ Checkout the repository
-  #     - name: Checkout repository
-  #       uses: actions/checkout@v3
+      # # 8️⃣ Generate Prisma client
+      # - name: Generate Prisma client
+      #   run: bunx prisma generate
 
-  #     # 2️⃣ Create .env from the secret
-  #     - name: Create .env
-  #       run: printf "%s\n" "${{ secrets.ENV }}" > .env
+      # 9️⃣ Run unit tests
+      - name: Run unit tests
+        run: bun run test:unit
 
-  #     # 3️⃣ Start containers, wait for DB, apply migrations & seed and prepare node enviroment for Vitest
-  #     - name: Set up Stage Docker Compose
-  #       env:
-  #         DATABASE_URL: postgresql://dart:nghk98734@db:5432/postgresdb
-  #         POSTGRES_USER: dart
-  #         POSTGRES_PASSWORD: nghk98734
-  #         POSTGRES_DB: postgresdb
-  #         PORT: 3000
-  #       run: docker compose --profile stage up --build -d
+  integration-tests:
+    name: Run Integration Tests in Docker
+    runs-on: ubuntu-latest
+    needs: build-and-test
 
-  #     - name: Wait for PostgreSQL
-  #       run: |
-  #         ATTEMPTS=0
-  #         MAX_ATTEMPTS=15
-  #         until docker compose exec -T db pg_isready -U dart > /dev/null 2>&1; do
-  #           echo "Waiting for database..."
-  #           sleep 2
-  #           ATTEMPTS=$((ATTEMPTS+1))
-  #           if [ $ATTEMPTS -ge $MAX_ATTEMPTS ]; then
-  #             echo "Database did not become ready in time."
-  #             exit 1
-  #           fi
-  #         done
+    steps:
+      # 1️⃣ Checkout the repository
+      - name: Checkout repository
+        uses: actions/checkout@v3
 
-  #     # 4️⃣ Run tests (coverage)
-  #     - name: Run tests (unit & integration)
-  #       run: docker compose run --rm app4-stage bun run test:coverage
+      # 2️⃣ Create .env from the secret
+      - name: Create .env
+        run: printf "%s\n" "${{ secrets.ENV }}" > .env
 
-  #     # # 5️⃣ Copiar pasta de coverage do container para o host
-  #     # - name: Copy coverage folder
-  #     #   run: docker cp $(docker compose ps -q app4):/usr/src/app/coverage ./coverage
+      # 3️⃣ Start containers, wait for DB, apply migrations & seed and prepare node enviroment for Vitest
+      - name: Set up Stage Docker Compose
+        env:
+          DATABASE_URL: postgresql://dart:nghk98734@db:5432/postgresdb
+          POSTGRES_USER: dart
+          POSTGRES_PASSWORD: nghk98734
+          POSTGRES_DB: postgresdb
+          PORT: 3000
+        run: docker compose --profile stage up --build -d
 
-  #     # # 6️⃣ Instalar sonar-scanner e dependências
-  #     # - name: Set up SonarQube scanner
-  #     #   uses: sonarsource/sonarcloud-github-action@v2
-  #     #   with:
-  #     #     args: >
-  #     #       -Dsonar.organization=devdartjs
-  #     #       -Dsonar.projectKey=Virtus-backend
-  #     #       -Dsonar.host.url=https://sonarcloud.io
-  #     #       -Dsonar.login=${{ secrets.SONAR_TOKEN }}
-  #     #       -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
+      - name: Wait for PostgreSQL
+        run: |
+          ATTEMPTS=0
+          MAX_ATTEMPTS=15
+          until docker compose exec -T db pg_isready -U dart > /dev/null 2>&1; do
+            echo "Waiting for database..."
+            sleep 2
+            ATTEMPTS=$((ATTEMPTS+1))
+            if [ $ATTEMPTS -ge $MAX_ATTEMPTS ]; then
+              echo "Database did not become ready in time."
+              exit 1
+            fi
+          done
 
-  #     # 7️⃣ Tear down Docker containers
-  #     - name: Tear down containers
-  #       if: always()
-  #       run: docker compose down --volumes --remove-orphans
+      # 4️⃣ Run tests (coverage)
+      - name: Run tests (unit & integration)
+        run: docker compose run --rm app4-stage bun run test:coverage
 
-  #     # 8️⃣ Clean up the .env file
-  #     - name: Cleanup .env
-  #       run: rm -f .env
+      # 5️⃣ Tear down Docker containers
+      - name: Tear down containers
+        if: always()
+        run: docker compose down --volumes --remove-orphans
+
+      # 6️⃣ Clean up the .env file
+      - name: Cleanup .env
+        run: rm -f .env
 
   build-and-push-image:
     name: Build & Push Docker Image
     runs-on: ubuntu-latest
-    # needs: integration-tests
+    needs: integration-tests
 
     steps:
       # 1️⃣ Checkout repository
@@ -194,9 +186,8 @@ jobs:
       - name: Set Fly secrets and Deploy to Stage
         run: |
           flyctl secrets set \
-            DATABASE_URL="${{ secrets.DATABASE_URL_STAGE_PG_FLY_SSLDISABLE }}" \
-            REDIS_URL="${{ secrets.REDIS_URL }}" \
-            REDIS_PASSWORD="${{ secrets.REDIS_PASSWORD }}" \
+            REDIS_URL_CLOUD="${{ secrets.REDIS_URL_CLOUD }}" \
+            DATABASE_URL_STAGE_NEON="${{ secrets.DATABASE_URL_STAGE_NEON }}" \
             BUN_ENV=stage \
             BASE_URL=https://app-wild-dust-1031.fly.dev \
             CACHE_TTL=3600 \
